name: update docs/storybook
on:
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout '${{ github.ref_name }}'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: configure git
      run: |
        git --version
        git config user.name "github-actions"
        git config user.email "<>"

    - name: prepare 'build-docs' branch
      run: |
        git checkout build-docs
        git reset --hard ${{ github.ref_name }}
    
    - name: setup bun environment
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: build docs
      run: |
        bun install
        bun run build-docs

    - name: deploy docs
      run: |
        git add ./docs
        git commit -m "chore(docs): update docs/storybook [auto]" --no-verify
        git push origin build-docs --force
